# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dnd-api-service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://dnd1registry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e37a2d02dfc4451c990f0ea5e24fe648 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a62c05afae16490ca7c4f72b5ecc9551 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: dnd1registry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e37a2d02dfc4451c990f0ea5e24fe648 }}/dnd-api:${{ github.sha }}
        file:  ./Backend/DndPersonality/DndPersonality/Dockerfile
        context:  ./Backend/DndPersonality/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dnd-api-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_278faaf7843440b1950bd23e110ea70c }}
        images: 'dnd1registry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e37a2d02dfc4451c990f0ea5e24fe648 }}/dnd-api:${{ github.sha }}'
